version: '3.8'

services:
  rabbitmq:
    image: rabbitmq:3.13-management
    container_name: petlogilink-rabbitmq
    ports:
      - "5672:5672"   # Puerto principal AMQP
      - "15672:15672" # Puerto del panel de Management UI
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq

volumes:
  rabbitmq_data:
